# -*- coding: utf-8 -*-
"""homework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvtfECUzeeTR3o3LQWO6bGoMNlD3Wqh6
"""

tr_harfler = "şçöğüİı"

for harf in tr_harfler:
    print(harf)

list_odd =[1,3,5,7]
list_even =[2,4,6,8]
mylist = list_odd + list_even
mylist.sort()
for i in mylist:
  result=i*2
  print(result)
for i in mylist:
  result=i*2  
  print("the type of",result," :",type(result))